export type Project = {
  id: string;
  title: string;
  summary: string;
  context: "BTS" | "perso" | "pro";
  category: string;
  role: string;
  shortOutcome: string;
  problem: string;
  solution: string;
  mainFeatures: string[];
  technicalHighlights: string[];
  challenges: string[];
  learnings: string[];
  featured: boolean;
  order: number;
  contextDetails?: string;
  description?: string[];
  features?: string[];
  stack: string[];
  competences: string[];
  badges: string[];
  screenshots?: string[];
  date: string;
  status: string;
  statusNote?: string;
  githubUrl?: string;
  demoUrl?: string;
};
